language: python

python:
  - "3.6"

sudo: false
cache: pip

addons:
  postgresql: "10"
  apt:
    packages:
      - expect-dev  # provides unbuffer utility
      - python-lxml  # because pip installation is slow

env:
  global:
  - VERSION="14.0" TESTS="0" LINT_CHECK="0"
  - PHANTOMJS_VERSION="latest"
  # To run javascript tests via Phantom JS.
  # - INCLUDE_EXTRA="web"
  matrix:
  # - LINT_CHECK="1"
  # - TESTS="1" ODOO_REPO="OCA/OCB"
  - TESTS="1" ODOO_REPO="odoo/odoo"


install:
  - git clone --depth=1 https://github.com/oerp-odoo/maintainer-quality-tools.git ${HOME}/maintainer-quality-tools
  - export PATH=${HOME}/maintainer-quality-tools/travis:${PATH}
  - travis_install_nightly

script:
  - travis_run_tests

after_success:
  - travis_after_tests_success
