UNKNOWN = 'unknown'
LATITUDE_LOWER_BOUND = -90
LATITUDE_UPPER_BOUND = 90
LONGITUDE_LOWER_BOUND = -180
LONGITUDE_UPPER_BOUND = 180
DEFAULT_DELIMITER = ','
KM_PER_DEGREE_LATITUDE = 111
METERS_IN_KM = 1000

OP_EQ_MAP = {True: '=ilike', False: '='}
