---
name: tests
on:
  pull_request:
  push:
    branches:
      - "19.0"

jobs:
  test:
    runs-on: ubuntu-22.04
    container: ghcr.io/oerp-odoo/oca-ci/py3.12-odoo19.0:latest
    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_USER: odoo
          POSTGRES_PASSWORD: odoo
          POSTGRES_DB: odoo
        ports:
          - 5432:5432
    env:
      OCA_ENABLE_CHECKLOG_ODOO: "1"
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
      - name: Install addons and dependencies
        run: oca_install_addons
      - name: Initialize test db
        run: oca_init_test_database
      - name: Run tests
        run: oca_run_tests
